### PR TITLE
Russian (русский) translation.

### PR DESCRIPTION
**Pull request by Zensonaton**
Hello, this is mine translation of your mod to Russian language. (`ru_ru`)
And yes, I know that this is probably not a greatest time for making a localization like this :D

However, when making such a translation, I've got into issue that some of the dynamically created tool names *(?)* like "`Diamond`+` shovel`", "`Molten gold`+` bucket`", etc, is pretty much impossible to translate due to how Russian language work. *(this is probably an issue that will occur with other languages other than English)* 
My suggestion to that issue is to allow translators to define full names ("exclusions") for the tools, item parts. For example:

```jsonc
// lang-file

"items.mod.shovel": "%d shovel"
"items.mod.shovel_gold": "This is a new name for the golden shovel!"
```
will be displayed in-game as:
```plain
Materialname shovel
This is a new name for the golden shovel!
```

### CODE REVIEW

**Comment by sussy-syrup** [comment]
Hello, thank you for taking the time to write this translation. I am not accepting your pull request just yet as I am implementing a solution for the issue you have mentioned. Thank you for bringing my attention to it and waiting for my response

**Comment by sussy-syrup** [comment]
I have pushed an alternative translation key provider which can selectively provide translation keys individually for each material-tool combo (the same applies to casts, tool parts and buckets too). I am going to leave the choice of including the translations you have already kindly made or to use the new system instead to you. Thank you again

**Comment by sussy-syrup** [comment]
Implemented a translation mode via json config in the usual config directory. When disabled, translations will default to the full translation and should one not exist to the combo translation as used in en_us. Enabling it will force the translations to always be full for an enabled language even if they do not exist. This should increase overall compatibility with languages that require full translations but they dont exist while still making it possible to translate

**Review by zrpvjpeg — CHANGES_REQUESTED** [review]
👌

**Review by zrpvjpeg — APPROVED** [review]
.

**Pull request merged**
